### ISSUE TITLE
Replace `.trace` with `command=`

### ISSUE THREAD

**Issue by WK-GiHu** [JDJacinto29/StackOverflow#5]
@WK-GiHu Ah got it. Ok with those changes, the user prompt that usually comes up when hitting "Add Custom..." is now bypassed, so I can't test it in the same way I was previously. However, repeatedly hitting the "Add Custom..." button does not seem to generate any errors

_Originally posted by @JDJacinto29 in https://github.com/JDJacinto29/StackOverflow/issues/4#issuecomment-573863375_

**Comment by WK-GiHu** [comment]
@JDJacinto29 

### Revert all changes in: https://github.com/JDJacinto29/StackOverflow/issues/4

Disable this Line 108
https://github.com/JDJacinto29/StackOverflow/blob/3638ef29ecc8ba2ad18eda0d643688cdf5620429/SetIPexample.py#L108

Change Line 104
https://github.com/JDJacinto29/StackOverflow/blob/3638ef29ecc8ba2ad18eda0d643688cdf5620429/SetIPexample.py#L104

to

```
 popupMenu = Tkinter.OptionMenu(frame, tkvar, *SiteIDs, command=changeSiteID) 
```

**Comment by JDJacinto29** [comment]
Ok got it, It's looking for those default positional arguments that are passed in when using option box commands like that. 

`
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\tkinter\__init__.py", line 1549, in __call__
    return self.func(*args)
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\tkinter\__init__.py", line 3287, in __call__
    self.__callback(self.__value, *args)
TypeError: changeSiteID() missing 2 required positional arguments: 'm' and 'x'

`

**Comment by WK-GiHu** [comment]
@JDJacinto29 

>TypeError: changeSiteID() missing 2 required positional arguments: 'm' and 'x'

Yes, the callback `def changeSiteID(n,m,x):` have to be `def changeSiteID():` for a `command=`
I wonder why ***missing 2 required***, there are ***3***?

**Comment by JDJacinto29** [comment]
@WK-GiHu Got it. When making that change, I get the below error. Looks like the hidden one is an automatically passed args?

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\tkinter\__init__.py", line 1549, in __call__
    return self.func(*args)
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\tkinter\__init__.py", line 3287, in __call__
    self.__callback(self.__value, *args)
TypeError: changeSiteID() takes 0 positional arguments but 1 was given

**Comment by WK-GiHu** [comment]
@JDJacinto29 

>Looks like the hidden one is an automatically passed args?

Can't explain it, ok make it happy with: `def changeSiteID(n)`.
To debug, add `print(type(n))` below to see which type of object get passed.

**Comment by JDJacinto29** [comment]
Output of the debugging line: <class 'str'>

I'm getting a different crash this time, looking into it now...

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\tkinter\__init__.py", line 1549, in __call__
    return self.func(*args)
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\tkinter\__init__.py", line 3287, in __call__
    self.__callback(self.__value, *args)
  File "C:\Users\jjacinto\Desktop\StackOverflow\SetIPexample.py", line 225, in changeSiteID
    addCustomSiteID()
  File "C:\Users\jjacinto\Desktop\StackOverflow\SetIPexample.py", line 216, in addCustomSiteID
    updateIP.set(defaultIP)
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\tkinter\__init__.py", line 260, in set
    return self._tk.globalsetvar(self._name, value)
_tkinter.TclError: can't set "PY_VAR1": 
Traceback (most recent call last):
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\tkinter\__init__.py", line 1549, in __call__
    return self.func(*args)
  File "C:\Users\jjacinto\Desktop\StackOverflow\SetIPexample.py", line 114, in <lambda>
    updateIP.trace("w", lambda index, mode, sv=updateIP: updateIPAdress())
  File "C:\Users\jjacinto\Desktop\StackOverflow\SetIPexample.py", line 242, in updateIPAdress
    with open(configFile, 'w') as configfile:
OSError: [Errno 22] Invalid argument: 'SetIPexample.ini'

**Comment by WK-GiHu** [comment]
@JDJacinto29 

### Your Tracebacks are hard to read, pleas `edit` the comment and enclose it into **three backticks***

**Comment by JDJacinto29** [comment]
@WK-GiHu edited, sorry about that. I  was wondering how you do that!

**Comment by WK-GiHu** [comment]
@JDJacinto29 

>

Disable the Line 113 for now:
https://github.com/JDJacinto29/StackOverflow/blob/3638ef29ecc8ba2ad18eda0d643688cdf5620429/SetIPexample.py#L113

**Comment by JDJacinto29** [comment]
@WK-GiHu Made the above changes, The debugging line now prints "Add Custom...", or, whichever menu option I happen to select. The program still crashed on the "OSError: [Errno 22] Invalid argument: 'SetIPexample.ini'" error (see other issue)

**Comment by JDJacinto29** [comment]
@WK-GiHu Sorry I had made the change but didn't commit yet. The latest commit has all of these changes now

**Comment by WK-GiHu** [comment]
@JDJacinto29 

Even with the disabled `updateIP.trace(...` did the changes from `.trace(...` to `command=` work?

**Comment by WK-GiHu** [comment]
>the script now appears to run without crashing.
